### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by JeffLIrion** [matejdro/AndroidTVRefresher#1]
1. What state information does this app send to HA?
2. Won't this information get overridden the next time HA updates the entity's state (which happens every 10 seconds by default)?

And FYI, I've used this ADB command to install apps:

```
adb shell pm install -r /sdcard/Download/something.apk
```

Combined with a command to download the APK (`curl` or `wget`), this should make installation of the app really easy.

**Comment by matejdro** [comment]
App only triggers `update_entity` service, which triggers poll request from HA:

https://github.com/matejdro/AndroidTVRefresher/blob/b34c86e28438c47617caf4555ec14856fd6e44f1/app/src/main/java/com/matejdro/androidtvrefresher/ListenerService.kt#L67

It does not push any events by itself, so there is no data inconsistency.

Does android have curl available natively? This would be a good way to install, yes. I will check.

**Comment by JeffLIrion** [comment]
Thanks for the clarification. I'll close this issue. 

> Does android have curl available natively?

I checked just now and my 2nd generation Fire TV stick has `curl`, so it's probably available on all Android devices.

**Comment by matejdro** [comment]
I've checked and Shield TV 2019 does not have either  `curl` or `wget` :/
